# ::: Code Generated by Copilot 0bd71c55-8ec0-4f78-9a6b-20a62f0b10b8. This comment will be removed automatically after the file is saved :::
import os

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import create_engine, text

# ::: Code Generated by Copilot 9fe6f17e-8b7e-4b2c-8d3a-5a6d5f8db2a1. This comment will be removed automatically after the file is saved :::
# This version saves items in a database instead of keeping them only in memory,
# so they are still there after the app is restarted.
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./shopping_list.db")


def get_engine_kwargs(database_url: str) -> dict[str, object]:
    # SQLite needs a thread-safe connection setting, but PostgreSQL does not.
    # This keeps local development working while allowing the Docker PostgreSQL setup to connect cleanly.
    if database_url.startswith("sqlite"):
        return {"connect_args": {"check_same_thread": False}, "pool_pre_ping": True}
    return {"pool_pre_ping": True}


engine = create_engine(DATABASE_URL, **get_engine_kwargs(DATABASE_URL))

app = FastAPI(title="Shared Shopping List")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ::: Code Generated by Copilot 9fe6f17e-8b7e-4b2c-8d3a-5a6d5f8db2a1. This comment will be removed automatically after the file is saved :::
# This setup runs when the app starts and creates the table if it does not exist,
# so the app can store and read items on the first run.
def init_db() -> None:
    with engine.begin() as conn:
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS items (
                    id INTEGER PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    quantity INTEGER NOT NULL DEFAULT 1,
                    completed BOOLEAN NOT NULL DEFAULT FALSE,
                    added_by VARCHAR(255) NOT NULL DEFAULT 'anonymous'
                )
                """
            )
        )


@app.on_event("startup")
def startup() -> None:
    init_db()


@app.get("/")
def root() -> dict[str, str]:
    return {"message": "Shared shopping list API is running. Use /items to view or add items."}


@app.get("/items")
def get_items() -> list[dict[str, object]]:
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT id, name, quantity, completed, added_by FROM items ORDER BY id")
        ).mappings().all()

    return [dict(row) for row in rows]


# ::: Code Generated by Copilot 9fe6f17e-8b7e-4b2c-8d3a-5a6d5f8db2a1. This comment will be removed automatically after the file is saved :::
# This part checks the input before saving it. It helps prevent empty names or bad
# quantities from causing problems in the app.
@app.post("/items", status_code=status.HTTP_201_CREATED)
async def add_item(request: Request) -> dict[str, object]:
    body = await request.json()
    name = (body.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=422, detail="name is required")

    try:
        quantity = int(body.get("quantity", 1))
    except (TypeError, ValueError):
        raise HTTPException(status_code=422, detail="quantity must be an integer") from None

    if quantity < 1:
        raise HTTPException(status_code=422, detail="quantity must be at least 1")

    added_by = (body.get("added_by") or "anonymous").strip() or "anonymous"

    with engine.begin() as conn:
        next_id = conn.execute(text("SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM items")).scalar_one()
        conn.execute(
            text(
                """
                INSERT INTO items (id, name, quantity, completed, added_by)
                VALUES (:id, :name, :quantity, FALSE, :added_by)
                """
            ),
            {"id": next_id, "name": name, "quantity": quantity, "added_by": added_by},
        )

    return {"id": next_id, "name": name, "quantity": quantity, "completed": False, "added_by": added_by}


# ::: Code Generated by Copilot 9fe6f17e-8b7e-4b2c-8d3a-5a6d5f8db2a1. This comment will be removed automatically after the file is saved :::
# These routes now update or delete items from the database. If an item is missing,
# the app returns a clear error instead of failing silently.
@app.patch("/items/{item_id}/complete")
async def complete_item(item_id: int) -> dict[str, object]:
    with engine.begin() as conn:
        result = conn.execute(text("UPDATE items SET completed = TRUE WHERE id = :item_id"), {"item_id": item_id})
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail="item not found")

        row = conn.execute(
            text("SELECT id, name, quantity, completed, added_by FROM items WHERE id = :item_id"),
            {"item_id": item_id},
        ).mappings().one()

    return dict(row)


@app.delete("/items/{item_id}")
async def delete_item(item_id: int) -> dict[str, object]:
    with engine.begin() as conn:
        result = conn.execute(text("DELETE FROM items WHERE id = :item_id"), {"item_id": item_id})
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail="item not found")

    return {"success": True}
