# ::: Code Generated by Copilot 0bd71c55-8ec0-4f78-9a6b-20a62f0b10b8. This comment will be removed automatically after the file is saved :::
import os
import sys
import unittest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from main import get_engine_kwargs


class DatabaseEngineTests(unittest.TestCase):
    def test_sqlite_engine_kwargs_include_check_same_thread(self) -> None:
        kwargs = get_engine_kwargs("sqlite:///./shopping_list.db")
        self.assertEqual(kwargs["connect_args"], {"check_same_thread": False})

    def test_postgres_engine_kwargs_do_not_include_sqlite_flag(self) -> None:
        kwargs = get_engine_kwargs("postgresql+psycopg2://postgres:postgres@db:5432/shoppinglist")
        self.assertNotIn("connect_args", kwargs)


if __name__ == "__main__":
    unittest.main()
