// ::: Code Generated by Copilot 0bd71c55-8ec0-4f78-9a6b-20a62f0b10b8. This comment will be removed automatically after the file is saved :::
import { useState, useEffect } from "react";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

export default function App() {
  const [items, setItems] = useState([]);
  const [newItemName, setNewItemName] = useState("");
  const [quantity, setQuantity] = useState(1);
  const [addedBy, setAddedBy] = useState("");
  // FLAW: No loading or error state — UI has no feedback during slow operations
  // like the 3-second blocking complete endpoint

  // FLAW: Fetches on mount but never re-fetches (no polling, no websocket).
  // If another user adds an item, this client never sees it without a manual refresh.
  useEffect(() => {
    fetch(`${API_URL}/items`)
      .then((res) => res.json())
      .then((data) => setItems(data));
  }, []);

  const handleAddItem = () => {
    if (!newItemName) return;

    // FLAW (NAIVE STATE MANAGEMENT): Optimistically appends a fake local item
    // immediately, THEN fires the real API call. If the API call fails or
    // returns a different ID, the local state is now out of sync with the server.
    const optimisticItem = {
      id: Math.random(), // FLAW: fake random ID will never match server's real ID
      name: newItemName,
      quantity: quantity, // FLAW: not validated — user could type "abc" or leave it 0
      completed: false,
      added_by: addedBy,
    };
    setItems((prev) => [...prev, optimisticItem]);

    fetch(`${API_URL}/items`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newItemName, quantity: quantity, added_by: addedBy }),
    })
      .then((res) => res.json())
      .then(() => {
        // FLAW: Ignores the server response entirely — never replaces the optimistic
        // item with the real server item. The fake random ID persists in state.
        // Clicking "complete" or "delete" on this item will send the wrong ID.
        setNewItemName("");
        setQuantity(1);
        setAddedBy("");
      });
    // FLAW: No .catch() — silent failure if the network is down
  };

  const handleComplete = (id) => {
    // FLAW (DOUBLE-TRIGGER): No disabled state set before the async call.
    // If the user clicks twice quickly, two PATCH requests fire simultaneously.
    // The server also sleeps 3s per request, so the UI hangs with zero feedback.
    fetch(`${API_URL}/items/${id}/complete`, { method: "PATCH" })
      .then((res) => res.json())
      .then((updatedItem) => {
        // FLAW: Mutates items by rebuilding array without checking for errors
        setItems((prev) =>
          prev.map((item) =>
            item.id === id ? { ...item, completed: true } : item
          )
        );
      });
    // FLAW: No loading indicator — button stays clickable during the 3s sleep
  };

  const handleDelete = (id) => {
    // FLAW: Deletes from local state immediately before confirming server success
    setItems((prev) => prev.filter((item) => item.id !== id));

    fetch(`${API_URL}/items/${id}`, { method: "DELETE" });
    // FLAW: No .then() or .catch() — fire and forget.
    // If delete fails, the item disappears from UI but still exists on the server.
  };

  return (
    <div style={{ maxWidth: "600px", margin: "40px auto", fontFamily: "sans-serif" }}>
      <h1>🧺 Shared Kitchen Shopping List</h1>

      <div style={{ display: "flex", gap: "8px", marginBottom: "24px", flexWrap: "wrap" }}>
        <input
          type="text"
          placeholder="Item name (e.g. Oat Milk)"
          value={newItemName}
          onChange={(e) => setNewItemName(e.target.value)}
          // FLAW: No onKeyDown Enter handler — users expect to press Enter to submit
          style={{ flex: 1, padding: "8px", fontSize: "16px" }}
        />
        <input
          type="number"
          placeholder="Qty"
          value={quantity}
          min="1"
          onChange={(e) => setQuantity(e.target.value)}
          // FLAW: value is kept as a string from the input, not parsed to int.
          // The backend will receive "2" (string) instead of 2 (int).
          style={{ width: "60px", padding: "8px", fontSize: "16px" }}
        />
        <input
          type="text"
          placeholder="Your name"
          value={addedBy}
          onChange={(e) => setAddedBy(e.target.value)}
          style={{ width: "130px", padding: "8px", fontSize: "16px" }}
        />
        <button
          onClick={handleAddItem}
          style={{ padding: "8px 16px", fontSize: "16px", cursor: "pointer" }}
          // FLAW: Button is never disabled, so hammering it spams duplicate items
        >
          Add
        </button>
      </div>

      {items.length === 0 && (
        <p style={{ color: "#888" }}>No items yet. Add something above!</p>
      )}

      <ul style={{ listStyle: "none", padding: 0 }}>
        {items.map((item) => (
          <li
            key={item.id}  // FLAW: key is the random fake ID for optimistic items
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
              padding: "12px",
              marginBottom: "8px",
              background: item.completed ? "#e8f5e9" : "#f9f9f9",
              borderRadius: "6px",
              border: "1px solid #ddd",
              textDecoration: item.completed ? "line-through" : "none",
              color: item.completed ? "#888" : "#111",
            }}
          >
            <span style={{ flex: 1 }}>
              <strong>{item.name}</strong>
              <span style={{ fontSize: "13px", color: "#555", marginLeft: "8px" }}>
                ×{item.quantity ?? 1}
              </span>
              {item.added_by && (
                <span style={{ fontSize: "12px", color: "#aaa", marginLeft: "8px" }}>
                  by {item.added_by}
                </span>
              )}
            </span>

            {!item.completed && (
              <button
                onClick={() => handleComplete(item.id)}
                style={{
                  padding: "4px 10px",
                  background: "#4caf50",
                  color: "white",
                  border: "none",
                  borderRadius: "4px",
                  cursor: "pointer",
                  // FLAW: No disabled attribute during inflight request
                }}
              >
                ✓ Got it
              </button>
            )}

            <button
              onClick={() => handleDelete(item.id)}
              style={{
                padding: "4px 10px",
                background: "#f44336",
                color: "white",
                border: "none",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              ✕
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
